import './js/mob-menu.js';
import './js/mob-input.js';
import './js/toggle-mode.js';
import './js/toggle-mode.js';
import './js/navigations.js';
//import './js/createMarkupRead.js';
// import './js/add-to-read.js';
//import './js/search-read.js';
//import './js/read-remove-add-from-favorite';
import './js/renderRead';
import './js/pre-loader';
